### ISSUE TITLE
Missing links in quoted retweet content when syncing tweets to Crossbell using xSync service

### ISSUE THREAD

**Issue by pseudoyu** [Crossbell-Box/OperatorSync#62]
# Problem Description

When using xSync service to sync tweets to Crossbell blockchain, formatting errors occur in quoted retweets. Two links are added to the retweet content, but they are not displayed on Crossbell (both xChar and xFeeds).

The original tweet url is: https://twitter.com/pseudo_yu/status/1622861342372941824

The original content is:

```plaintext
真的很快！我之前折腾过一个无边框美化方案，而且可以通过一些黑科技把 Command+D 分屏，Command+T 开新 Tab 这些通用快捷键结合 Tmux 里也能用，折腾性很强，早就作为默认终端了。

教程：https://www.pseudoyu.com/zh/2022/07/10/my_config_and_beautify_solution_of_macos_terminal/

dotfile：https://github.com/pseudoyu/dotfiles/blob/master/alacritty/alacritty.yml

<Original Tweet>
```

The displayed synced content is:

```plaintext
真的很快！我之前折腾过一个无边框美化方案，而且可以通过一些黑科技把 Command+D 分屏，Command+T 开新 Tab 这些通用快捷键结合 Tmux 里也能用，折腾性很强，早就作为默认终端了。

教程：

dotfile：



Tw93: #工程师工具 最近发现一个性能很好的终端叫做「Alacritty」，传说中最快的终端，基于 Rust 使用 OpenGL 加速同时支持跨平台，只有 5M 大小，不过是真的丑，上周末想着要是我来做应该是什么样子，于是乎就改良了一番，最后效果还不错，已成默认终端，写了一篇教程记录了下。
🤖
 https://tw93.fun/2023-01-25/alacritty.html
```

# Related Account

The Crossbell address affected by this issue is `0xb461c1521eE9D96a9C950337f0851b79bD66CAe1`

# Screenshots

![image](https://user-images.githubusercontent.com/69753389/217200777-9ff4a568-aedb-4e1a-aa4b-cf3a1ba16b19.png)

![image](https://user-images.githubusercontent.com/69753389/217200828-f9541b8f-f334-4136-918f-27e6cdb54af4.png)

**Comment by DIYgod** [comment]
Thanks for the report, this problem has been fixed in https://github.com/DIYgod/RSSHub/commit/6d93d13a7eb30756e911c4a2620c11740977dec1

If there are still any problems please feel free to reopen.
